### ISSUE TITLE
Lack of Borger

### ISSUE THREAD

**Issue by Emil-Ilnicki** [thedansilva/SudokuMaster#5]
@mdalmaruf @HausdorfB @thedansilva @sid-tripathi @andabanda 
> "Borger" - borgie man

BURGER (for reference)
![istockphoto-1188412964-612x612](https://user-images.githubusercontent.com/28817337/144118253-43eb5ed0-8c9e-4742-9438-c7160bae0603.jpeg)
```typescript
import {meatChoices, vegChoices, chezChoices} from '../../Helpers/Types/FileIDontWantToProgramCuzLazy'

// dons run? 😳 

interface IInternals {
    meat?: Array<meatChoices>
    veg?: Array<vegChoices>
    cheese?: Array<chezChoices>
}

interface IBurgerData {
    buns: IInternals
}

export const borger = async (callback: (burgerData : IBurgerData)) : Promise<void> => {
    const borgie = {
        buns: {
            meat: [juicy meat, quarter pounder meat, thicc meat], 
           cheese: [gooda cheez, cheddar cheez]
        }
   }

     const eatBorger = await callback(borgie).then(console.log("Borger was eaten. What a good borgie"))
}


export default borger
```
Plox add to code base. will improve! 💯 👍
### **Tasks**

- [x] Add to code base for insta win 😎
- [ ] Add Sauce interface for more epic borgies 👁️ 👄 👁️

**Comment by Emil-Ilnicki** [comment]
Thoughts?

**Comment by HausdorfB** [comment]
Hmm.. seems pretty Borger to me

**Comment by Emil-Ilnicki** [comment]
<img width="907" alt="Screen Shot 2021-11-30 at 3 31 15 PM" src="https://user-images.githubusercontent.com/28817337/144123967-6694e0f2-2986-4f52-8084-a956ed6296a6.png">


![bruh-faint](https://user-images.githubusercontent.com/28817337/144123974-3cfe8a8e-918d-46e5-801a-b43820e950b2.gif)

**Comment by thedansilva** [comment]
hi Emile ,  will push commit To Github git gerrit git after work.  notice that This JAvascrmipt. Can I put in Javo ? ? ? ? File??

**Comment by thedansilva** [comment]
![me-explaining-how-me-when-the](https://user-images.githubusercontent.com/43654534/144307613-ab23d176-04ac-4350-b7fb-c86695702d56.gif)

**Comment by Emil-Ilnicki** [comment]
Uhhhhhhhhhhhhhhh ummm uhh uhhhhhhhhhh what javo

**Comment by andabanda** [comment]
Hi there,

Just wanted to inform everyone on this email chain that this repo has been
inactive for some time and therefore has been marked as: [INACTIVE].

If you would like to continue using this repo, please reenter your payment
method in your account settings so that this repo can stay open.

Thanks,
The GitHub team

**Comment by thedansilva** [comment]
Please see commit 71d982a10502672527965a11c33561777049abde. Burger has been added to sudoku Master github Git.

**Comment by Emil-Ilnicki** [comment]
UHMMMMMMMMM its supposed to be a typescripts file

**Comment by thedansilva** [comment]
On Dec. 2, 2021 13:33, Emil Ilnicki ***@***.***> wrote:
UHMMMMMMMMM its supposed to be a typescripts file

**Comment by thedansilva** [comment]
![image](https://user-images.githubusercontent.com/43654534/144667013-c6289d62-5f8c-49b7-a8cb-093ac5bf2c0a.png)
I DON CARE
